### ISSUE TITLE
Tetration TSA - Frank Dagenhardt - Lab Access

### ISSUE THREAD

**Issue by fdagen** [deftcon/Tetration-Virtual-Bootcamp#1]
Would you mind adding my AWS Account ID so that I may copy the AMIs over and perform the lab?

Your AWS Account Number here:400489367486

Issues with providing your AWS Act ID here? 
No worries. Simply send an email to tvb@deftcon.io with this info and we will get it taken care of on the DL.

**Comment by highspeedsnow** [comment]
Hi,

OK, you should be ready to begin copying AMIs as the permissions have been assigned to your account.

Please be sure to follow this process:

1) Click [here to subscribe to the Kali Linux image from AWS Marketplace](https://aws.amazon.com/marketplace/pp?sku=89bab4k3h9x4rkojcm2tj8j4l) necessary for the MITRE ATT&CK server, then [here to subscribe to the CentOS7 Linux image from AWS Marketplace](https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce) necessary for much of the lab environment, and finally [click here to subscribe to the Cisco ASAv image from AWS Marketplace](https://aws.amazon.com/marketplace/pp/B00WRGASUC) necessary for the Virtual ASA that separates the pseudo corporate from the pseudo internet using the BYOL license model. 

2) Verify that you now have at least these three subscriptions [here in your view of the AWS Marketplace](https://console.aws.amazon.com/marketplace/home?region=us-east-1#/subscriptions?Feedback=true)

3) Clone the git repo
`git clone https://github.com/deftcon/Tetration-Virtual-Bootcamp/`

4) Change directory to lab-env-build
`cd lab-env-build`

5) Be sure you have Python 3.7 or later (will not work with python 2.7)
`python --version`
_`Python 3.8.5`_

6) Install python requirements (dependancies)
`pip install -r requirements.txt`

7) Next, you will also need to retrieve your AWS API Keys and export them as environment variables in your terminal session as shown below:
`export AWS_ACCESS_KEY_ID=<YOUR AWS ACCESS KEY>`
`export AWS_SECRET_ACCESS_KEY=<YOUR AWS SECRET KEY>`

Generating API keys can be accomplished by navigating to the Identity and Access Management (IAM) service in the AWS console. Under Users, select your user account and click on the Security credentials tab.

8) Run the script to copy the AMIs to your ultimate destination region (will copy to us-east-2/Ohio first and later delete if not final region)
`python ami_create.py --region us-west-2`

9) Launch the lab environment process (questions will guide you through the rest)
`python launch.py`

Enjoy and please provide feedback with [bugs](https://github.com/deftcon/Tetration-Virtual-Bootcamp/issues/new?template=bug_report.md), feature [requests](https://github.com/deftcon/Tetration-Virtual-Bootcamp/issues/new?template=feature_request.md), and other [use-cases](https://github.com/deftcon/Tetration-Virtual-Bootcamp/issues/new?template=use_case.md) you may find use for. 

Enjoy!

**Comment by fdagen** [comment]
Hey Mark,

Getting an issue when I run the ami_create.py script.


2020-10-29 15:52:01,357 - INFO - Creating EC2 image ami_create_tmp-cisco-hol-ami-attacker-kali-debian-final

Traceback (most recent call last):

  File "/Users/fdagenha/Projects/Tetration-Virtual-Bootcamp/lab-env-build/ami_create.py", line 28, in <module>

    instances = ec2_ohio.create_instances(

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/boto3/resources/factory.py", line 520, in do_action

    response = action(self, *args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/boto3/resources/action.py", line 83, in __call__

    response = getattr(parent.meta.client, operation_name)(*args, **params)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call

    return self._make_api_call(operation_name, kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call

    raise error_class(parsed_response, operation_name)

botocore.exceptions.ClientError: An error occurred (OptInRequired) when calling the RunInstances operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=89bab4k3h9x4rkojcm2tj8j4l

I have subscribed to the products you listed below. Any thoughts?

Thanks,

Frank

**Comment by highspeedsnow** [comment]
Thanks Frank. Reply in email.
