### ISSUE TITLE
Access to AMIs

### ISSUE THREAD

**Issue by orlandocontreras94** [deftcon/Tetration-Virtual-Bootcamp#11]
Would you mind adding my AWS Account ID so that I may copy the AMIs over and perform the lab?

Your AWS Account Number here: 230797939087

Issues with providing your AWS Act ID here? 
No worries. Simply send an email to tvb@deftcon.io with this info and we will get it taken care of on the DL.

**Comment by highspeedsnow** [comment]
Hi Orlando, 

These AMIs have now been shared with your account. Please let us know if you have any issues.
