### ISSUE TITLE
Access to AMIs

### ISSUE THREAD

**Issue by jfernandohdz** [deftcon/Tetration-Virtual-Bootcamp#13]
Would you mind adding my AWS Account ID so that I may copy the AMIs over and perform the lab?

Your AWS Account Number here: 135747721119

Thank you

Issues with providing your AWS Act ID here? 
No worries. Simply send an email to tvb@deftcon.io with this info and we will get it taken care of on the DL.

**Comment by highspeedsnow** [comment]
done!
