### ISSUE TITLE
AWS-IAM

### ISSUE THREAD

**Issue by samytetration** [deftcon/Tetration-Virtual-Bootcamp#15]
Would you mind adding my AWS Account ID so that I may copy the AMIs over and perform the lab?

Your AWS Account Number here:678632507893 

Issues with providing your AWS Act ID here? 
No worries. Simply send an email to tvb@deftcon.io with this info and we will get it taken care of on the DL.

**Comment by highspeedsnow** [comment]
This has been completed. Many apologies for the delay.
