### ISSUE TITLE
AMI Access

### ISSUE THREAD

**Issue by jburcham** [deftcon/Tetration-Virtual-Bootcamp#2]
Would you mind adding my AWS Account ID so that I may copy the AMIs over and perform the lab?

Your AWS Account Number here: 239245830381

Issues with providing your AWS Act ID here? 
No worries. Simply send an email to tvb@deftcon.io with this info and we will get it taken care of on the DL.

**Comment by highspeedsnow** [comment]
Hi,

OK, you should be ready to begin copying AMIs as the permissions have been assigned to your account.

Please be sure to follow this process:

1) Click [here to subscribe to the Kali Linux image from AWS Marketplace](https://aws.amazon.com/marketplace/pp?sku=89bab4k3h9x4rkojcm2tj8j4l) necessary for the MITRE ATT&CK server.

2) Click [here to subscribe to the CentOS7 Linux image from AWS Marketplace](https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce) necessary for much of the lab environment.

3) Click [here to subscribe to the Cisco ASAv image from AWS Marketplace](https://aws.amazon.com/marketplace/pp/B00WRGASUC) necessary for the Virtual ASA that separates the pseudo corporate from the pseudo internet using the BYOL or Bring Your Own License model, which we forgo any licensing and just stick to the 100Kbps.

4) Clone the git repo
`git clone https://github.com/deftcon/Tetration-Virtual-Bootcamp/`

5) Change directory to lab-env-build
`cd lab-env-build`

6) Be sure you have Python 3.7 or later (will not work with python 2.7)
`python --version`
_`Python 3.8.5`_

7) Install python requirements (dependancies)
`pip install -r requirements.txt`

8) Next, you will also need to retrieve your AWS API Keys and export them as environment variables in your terminal session as shown below:
`export AWS_ACCESS_KEY_ID=<YOUR AWS ACCESS KEY>`
`export AWS_SECRET_ACCESS_KEY=<YOUR AWS SECRET KEY>`

Generating API keys can be accomplished by navigating to the Identity and Access Management (IAM) service in the AWS console. Under Users, select your user account and click on the Security credentials tab.

9) Run the script to copy the AMIs to your ultimate destination region (will copy to us-east-2/Ohio first and later delete if not final region)
`python ami_create.py --region us-west-2`

10) Launch the lab environment process (questions will guide you through the rest)
`python launch.py`

Enjoy and please provide feedback with [bugs](https://github.com/deftcon/Tetration-Virtual-Bootcamp/issues/new?template=bug_report.md), feature [requests](https://github.com/deftcon/Tetration-Virtual-Bootcamp/issues/new?template=feature_request.md), and other [use-cases](https://github.com/deftcon/Tetration-Virtual-Bootcamp/issues/new?template=use_case.md) you may find use for. 

Enjoy!

**Comment by jburcham** [comment]
Error on Step 8. 
"ubuntu@ip-172-31-9-227:~/Tetration-Virtual-Bootcamp/lab-env-build$ python3 ami_create.py --region us-west-1
2020-10-29 19:40:12,698 - INFO - Creating EC2 image ami_create_tmp-cisco-hol-cisco-student-00-ec2-active-directory-win-2019-us-east-2a
Traceback (most recent call last):
  File "ami_create.py", line 28, in <module>
.......
 File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials"

**Comment by highspeedsnow** [comment]
Just sent you an email with the update. Was in the lab-env-build readme, but not at all obvious with the summarized version that was replied with here. Have updated the response template so it doesn't affect others. Thanks for catching this.

Here is the part of the response that was missing, for others edification:


Next, you will also need to retrieve your AWS API Keys and export them as environment variables in your terminal session as shown below:

`export AWS_ACCESS_KEY_ID=<YOUR AWS ACCESS KEY>`
`export AWS_SECRET_ACCESS_KEY=<YOUR AWS SECRET KEY>`

Generating API keys can be accomplished by navigating to the Identity and Access Management (IAM) service in the AWS console. Under Users, select your user account and click on the Security credentials tab.
