### ISSUE TITLE
Access to AMIs

### ISSUE THREAD

**Issue by lsaliec** [deftcon/Tetration-Virtual-Bootcamp#8]
Would you mind adding my AWS Account ID so that I may copy the AMIs over and perform the lab?

Your AWS Account Number here: 487427127083

Issues with providing your AWS Act ID here? 
No worries. Simply send an email to tvb@deftcon.io with this info and we will get it taken care of on the DL.

**Comment by highspeedsnow** [comment]
You are good to go!

**Comment by highspeedsnow** [comment]
You should be good to go now. Simply run "python launch.py" and everything else, including copying the images to whatever target region you specify, will be automatically carried out for you!
